### ISSUE TITLE
New dotfiles

### ISSUE THREAD

**Issue by Jarvvski** [JLErvin/dofiles#1]
Hey, I saw your reddit post for https://gfycat.com/AshamedTemptingAntbear

Also saw that you're going through finals. Could you let me know when you put up your new stuff? I'd love that colorscheme and firefox theme!

**Comment by asnider6** [comment]
Good luck on finals, Go Dawgs! :)

**Comment by JLErvin** [comment]
My dotfiles are current right now. They are what I used on my most recent unixporn submission [here](https://www.reddit.com/r/unixporn/comments/5vw214/macoskwm_neovim_and_pretty_colors/)
