### ISSUE TITLE
Firefox theme

### ISSUE THREAD

**Issue by autoferrit** [JLErvin/dofiles#2]
I was wondering how you got your Firefox to look like it does in the second screenshot in the readme. Is this part of kwm? Or is it a Firefox theme? As I see no window bar (I believe because of kwm) oand there are no tabs.

Thanks

**Comment by JLErvin** [comment]
Hey sorry for the late response. Actually no, none of the firefox features are related to kwm. Sadly macOS will not allow any application to edit the appearance of windows like that. 

The firefox styling is done using a plugin called stylish. You can find it [here](https://addons.mozilla.org/en-US/firefox/addon/stylish/). The theme that I am using will automatically take away the title bar that comes with macOS. They should be available in my dot files.

**Comment by autoferrit** [comment]
awesome thanks.
